### ISSUE TITLE
Error: Missing helper: "m": Missing helper: "m"

### ISSUE THREAD

**Issue by Hotallday** [iiegor/xat-www#1]
nfo","name":"server","message":"Hapi server started @http://localhost:8080"}
Debug: internal, implementation, error
    Error: Missing helper: "m": Missing helper: "m"
    at Object.<anonymous> (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\helpers\helper-missing.js:19:13)
    at eval (eval at createFunctionContext (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:4:95)
    at Object.prog [as inverse] (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
    at Object.<anonymous> (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:17:22)
    at Object.eval (eval at createFunctionContext (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:12:32)
    at main (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at Object.renderer [as layout] (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:142:36)
    at C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:492:18
    at Object.renderer (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:148:28)
    at internals.Manager._render (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:477:14)
    at Object.internals.marshal (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:571:13)
    at internals.Response._marshal (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\hapi\lib\response.js:466:22)
    at C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\hapi\lib\transmit.js:121:18
    at C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\hapi\lib\transmit.js:557:20
Debug: internal, implementation, error
    Error: Missing helper: "m": Missing helper: "m"
    at Object.<anonymous> (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\helpers\helper-missing.js:19:13)
    at eval (eval at createFunctionContext (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:4:95)
    at Object.prog [as inverse] (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
    at Object.<anonymous> (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:17:22)
    at Object.eval (eval at createFunctionContext (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:12:32)
    at main (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at Object.renderer [as layout] (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:142:36)
    at C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:492:18
    at Object.renderer (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:148:28)
    at internals.Manager._render (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:477:14)
    at Object.internals.marshal (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\vision\lib\manager.js:571:13)
    at internals.Response._marshal (C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\hapi\lib\response.js:466:22)
    at C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\hapi\lib\transmit.js:121:18
    at C:\Users\RsTown\Desktop\Xat Tools\Xat Website Hapi\xat-www-master\node_modules\hapi\lib\transmit.js:557:20

Is there any way to fix it. I think it has to do with the version number of the packages.

**Comment by Hotallday** [comment]
Fixed it

**Comment by iiegor** [comment]
Hello, @Hotallday!

Was this an actual problem with ``xat-www`` or just a bad configuration problem? Thanks.

**Comment by Hotallday** [comment]
It was just a bad configuration problem.
